
package client.artefact;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PhasebookMainWSService", targetNamespace = "http://connector/", wsdlLocation = "http://127.0.0.1:8180/PhasebookMainWS/test?wsdl")
public class PhasebookMainWSService
    extends Service
{

    private final static URL PHASEBOOKMAINWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.artefact.PhasebookMainWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = client.artefact.PhasebookMainWSService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8180/PhasebookMainWS/test?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8180/PhasebookMainWS/test?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PHASEBOOKMAINWSSERVICE_WSDL_LOCATION = url;
    }

    public PhasebookMainWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhasebookMainWSService() {
        super(PHASEBOOKMAINWSSERVICE_WSDL_LOCATION, new QName("http://connector/", "PhasebookMainWSService"));
    }

    /**
     * 
     * @return
     *     returns PhasebookMainWS
     */
    @WebEndpoint(name = "PhasebookMainWSPort")
    public PhasebookMainWS getPhasebookMainWSPort() {
        return super.getPort(new QName("http://connector/", "PhasebookMainWSPort"), PhasebookMainWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PhasebookMainWS
     */
    @WebEndpoint(name = "PhasebookMainWSPort")
    public PhasebookMainWS getPhasebookMainWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://connector/", "PhasebookMainWSPort"), PhasebookMainWS.class, features);
    }

}
