
package client.artifact;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PhasebookMainWS", targetNamespace = "http://connector/")
public interface PhasebookMainWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "test", targetNamespace = "http://connector/", className = "client.artifact.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://connector/", className = "client.artifact.TestResponse")
    public String test(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
