
package client.artefact2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PhasebookMainWSService", targetNamespace = "http://connector/", wsdlLocation = "http://127.0.0.1:8180/PhasebookMainWS/test?wsdl")
public class PhasebookMainWSService
    extends Service
{

    private final static URL PHASEBOOKMAINWSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8180/PhasebookMainWS/test?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PHASEBOOKMAINWSSERVICE_WSDL_LOCATION = url;
    }

    public PhasebookMainWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PhasebookMainWSService() {
        super(PHASEBOOKMAINWSSERVICE_WSDL_LOCATION, new QName("http://connector/", "PhasebookMainWSService"));
    }

    /**
     * 
     * @return
     *     returns PhasebookMainWS
     */
    @WebEndpoint(name = "PhasebookMainWSPort")
    public PhasebookMainWS getPhasebookMainWSPort() {
        return (PhasebookMainWS)super.getPort(new QName("http://connector/", "PhasebookMainWSPort"), PhasebookMainWS.class);
    }

}
